version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    container_name: postgre_db_prod
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    container_name: backend_prod
    image: alvel007/foodgram_backend:latest
    env_file: .env
    volumes:
      - static_volume:/backend_static/
      - media_volume:/app/media/
    depends_on:
      - db
  frontend:
    container_name: frontend_prod
    image: alvel007/foodgram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static/
  gateway:
    container_name: nginx_prod
    image: alvel007/foodgram_gateway:latest
    env_file: .env
    volumes:
      - static_volume:/static/
      - media_volume:/app/media/
    ports:
      - 9080:80
    depends_on:
      - backend