version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: postgre_db_foodgram
    image: postgres:13.10
    env_file: .env
    volumes:
       - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  frontend:
    container_name: frontend_foodgram
    image: alvel007/foodgram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - ../frontend/:/app/result_build/
  backend:
    container_name: backend_foodgram
    image: alvel007/foodgram_backend:latest
    env_file: .env
    volumes:
      - static:/static
      - media:/app/media
    depends_on:
      - db
  gateway:
    container_name: nginx_gateway
    image: alvel007/foodgram_gateway:latest
    env_file: .env
    volumes:
      - /.nginx.conf:/etc/nginx/sites-enabled/default
      - static:/usr/share/nginx/html/
      - backend_static:/backend_static
      - backend_media:/backend_media
      - ../docs/:/usr/share/nginx/html/api/docs/
    ports:
      - 9080:80
    depends_on:
      - backend
    restart:
      always