version: '3.3' 
 
volumes: 
  static:
  backend_static:
  backend_media:
  pg_data:
 
services: 
  db:
    container_name: postgre_db_prod
    image: postgres:latest 
    environment:
      POSTGRES_USER: foodgram_user
      POSTGRES_PASSWORD: foodgram_password
      POSTGRES_DB: foodgram

    volumes: 
      - pg_data:/var/lib/postgresql/data 
    ports:
      - "5432:5432"
   
  backend: 
    image: alvel007/foodgram_backend:latest 
    env_file: ./.env 
    depends_on: 
      - db 
    volumes: 
      - backend_static:/app/static
      - backend_media:/app/media
   
  frontend: 
    image: alvel007/foodgram_frontend:latest 
    depends_on: 
      - backend 
    volumes: 
      - static:/app/result_build/build 
 
  nginx: 
    image: nginx:latest 
    env_file: ./.env 
    depends_on: 
      - frontend 
    ports: 
      - "8000:80" 
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 
      - static:/usr/share/nginx/html/
      - backend_static:/backend_static
      - backend_media:/backend_media
      - ../docs/:/usr/share/nginx/html/api/docs/